CREATE TABLE STUDENT_DATA (
    SID NUMBER,
    SNAME VARCHAR2(30),
    COURSE_ID NUMBER
);

CREATE TABLE COURSE_DATA (
    COURSE_ID NUMBER,
    COURSE_NAME VARCHAR2(30)
);

INSERT INTO STUDENT_DATA VALUES (1, 'RAJ', 101);
INSERT INTO STUDENT_DATA VALUES (2, 'ANU', 102);
INSERT INTO STUDENT_DATA VALUES (3, 'SIVA', 103);

INSERT INTO COURSE_DATA VALUES (101, 'JAVA');
INSERT INTO COURSE_DATA VALUES (102, 'PYTHON');
INSERT INTO COURSE_DATA VALUES (104, 'SQL');

-- INNER JOIN
SELECT S.SID, S.SNAME, C.COURSE_NAME
FROM STUDENT_DATA S
INNER JOIN COURSE_DATA C
ON S.COURSE_ID = C.COURSE_ID;

-- LEFT JOIN
SELECT S.SID, S.SNAME, C.COURSE_NAME
FROM STUDENT_DATA S
LEFT JOIN COURSE_DATA C
ON S.COURSE_ID = C.COURSE_ID;

-- RIGHT JOIN
SELECT S.SID, S.SNAME, C.COURSE_NAME
FROM STUDENT_DATA S
RIGHT JOIN COURSE_DATA C
ON S.COURSE_ID = C.COURSE_ID;
