CREATE TABLE STAFF_DATA (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(30),
    SALARY NUMBER
);

INSERT INTO STAFF_DATA VALUES (301, 'ARUN', 25000);
INSERT INTO STAFF_DATA VALUES (302, 'PRIYA', 40000);
INSERT INTO STAFF_DATA VALUES (303, 'VIMAL', 35000);
INSERT INTO STAFF_DATA VALUES (304, 'DIVYA', 50000);

SELECT EMP_ID, EMP_NAME, SALARY
FROM STAFF_DATA
WHERE SALARY > (
    SELECT AVG(SALARY)
    FROM STAFF_DATA
);
