SELECT ABS(-25) AS ABSOLUTE_VALUE
FROM DUAL;

SELECT CEIL(12.4) AS CEILING_VALUE
FROM DUAL;

SELECT FLOOR(12.8) AS FLOOR_VALUE
FROM DUAL;

SELECT MOD(25, 4) AS REMAINDER
FROM DUAL;

SELECT POWER(3, 3) AS POWER_VALUE
FROM DUAL;

SELECT ROUND(45.678, 2) AS ROUND_VALUE
FROM DUAL;
