DECLARE
    STR VARCHAR2(50) := 'DATABASE';
    REV VARCHAR2(50) := '';
BEGIN
    FOR I IN REVERSE 1..LENGTH(STR) LOOP
        REV := REV || SUBSTR(STR, I, 1);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('ORIGINAL STRING : ' || STR);
    DBMS_OUTPUT.PUT_LINE('REVERSED STRING : ' || REV);
END;
/
