CREATE TABLE PRODUCT (
    PRODUCT_ID NUMBER PRIMARY KEY,
    PRODUCT_NAME VARCHAR2(30) NOT NULL,
    PRICE NUMBER CHECK (PRICE > 0),
    EMAIL VARCHAR2(50) UNIQUE,
    CITY VARCHAR2(30) DEFAULT 'CHENNAI'
);

INSERT INTO PRODUCT
VALUES (201, 'LAPTOP', 55000, 'raj@gmail.com', 'CUDDALORE');

SELECT * FROM PRODUCT;
