CREATE TABLE MARK_DATA (
    ID NUMBER,
    NAME VARCHAR2(30),
    MARK NUMBER
);

INSERT INTO MARK_DATA VALUES (1, 'RAJ', 85);
INSERT INTO MARK_DATA VALUES (2, 'ANU', 72);
INSERT INTO MARK_DATA VALUES (3, 'SIVA', 90);
INSERT INTO MARK_DATA VALUES (4, 'PRIYA', 78);
INSERT INTO MARK_DATA VALUES (5, 'VIMAL', 95);

SELECT COUNT(MARK) AS TOTAL_STUDENTS
FROM MARK_DATA;

SELECT SUM(MARK) AS TOTAL_MARK
FROM MARK_DATA;

SELECT AVG(MARK) AS AVERAGE_MARK
FROM MARK_DATA;

SELECT MAX(MARK) AS HIGHEST_MARK
FROM MARK_DATA;

SELECT MIN(MARK) AS LOWEST_MARK
FROM MARK_DATA;
