CREATE TABLE EMPLOYEE_LOG (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR2(50),
    ACTION_DATE DATE
);
CREATE OR REPLACE TRIGGER EMPLOYEE_DELETE_TRIGGER
AFTER DELETE ON EMPLOYEE
FOR EACH ROW
BEGIN
    INSERT INTO EMPLOYEE_LOG
    VALUES (:OLD.EMP_ID, :OLD.EMP_NAME, SYSDATE);
END;
/
DELETE FROM EMPLOYEE
WHERE EMP_ID = 104;

SELECT * FROM EMPLOYEE_LOG;
