DECLARE
    CURSOR EMP_CURSOR IS
        SELECT EMP_ID, EMP_NAME, SALARY
        FROM EMPLOYEE;

    V_ID EMPLOYEE.EMP_ID%TYPE;
    V_NAME EMPLOYEE.EMP_NAME%TYPE;
    V_SALARY EMPLOYEE.SALARY%TYPE;

BEGIN
    OPEN EMP_CURSOR;

    LOOP
        FETCH EMP_CURSOR INTO V_ID, V_NAME, V_SALARY;

        EXIT WHEN EMP_CURSOR%NOTFOUND;

        DBMS_OUTPUT.PUT_LINE(
            'ID: ' || V_ID ||
            '  NAME: ' || V_NAME ||
            '  SALARY: ' || V_SALARY
        );
    END LOOP;

    CLOSE EMP_CURSOR;
END;
/
