CREATE TABLE TEAM_A (
    ID NUMBER,
    NAME VARCHAR2(30)
);

CREATE TABLE TEAM_B (
    ID NUMBER,
    NAME VARCHAR2(30)
);

INSERT INTO TEAM_A VALUES (101, 'RAJ');
INSERT INTO TEAM_A VALUES (102, 'KUMAR');
INSERT INTO TEAM_A VALUES (103, 'ANU');

INSERT INTO TEAM_B VALUES (102, 'KUMAR');
INSERT INTO TEAM_B VALUES (103, 'ANU');
INSERT INTO TEAM_B VALUES (104, 'SIVA');

COMMIT;

-- UNION
SELECT ID, NAME FROM TEAM_A
UNION
SELECT ID, NAME FROM TEAM_B;

-- UNION ALL
SELECT ID, NAME FROM TEAM_A
UNION ALL
SELECT ID, NAME FROM TEAM_B;

-- INTERSECT
SELECT ID, NAME FROM TEAM_A
INTERSECT
SELECT ID, NAME FROM TEAM_B;

-- MINUS
SELECT ID, NAME FROM TEAM_A
MINUS
SELECT ID, NAME FROM TEAM_B;
