SELECT UPPER('oracle') FROM DUAL;

SELECT LOWER('DATABASE') FROM DUAL;

SELECT LENGTH('PROGRAMMING') FROM DUAL;

SELECT INITCAP('database management system')
FROM DUAL;

SELECT SUBSTR('COMPUTER', 1, 4)
FROM DUAL;

SELECT REPLACE('WELCOME TO SQL', 'SQL', 'ORACLE')
FROM DUAL;
